In [2]:
import numpy as np

x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


converting list to the array

In [5]:
l=[]
for i in range(1,4):
    x =int(input())
    l.append(x)
array = np.array(l)
print(array)

12
12
13
[12 12 13]


creating two dimensional arrays 

In [10]:
two = np.array([[1,2,3],[4,5,6],[7,4,6]])
print(two)
print(two.ndim)

[[1 2 3]
 [4 5 6]
 [7 4 6]]
2


creating three dimensional array 

In [11]:
three = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(two,two.ndim)

[[1 2 3]
 [4 5 6]
 [7 4 6]] 2


creating an n dimensional array   - ndmin - function is used create n dimentional arrays 

In [14]:
ndimen = np.array([1,2,3],ndmin =10)
print(ndimen)
print(ndimen.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


special numpy arrays  --

array filled with zeros  - using method np.zeros 


In [17]:
zeros = np.zeros(4)
print(zeros)
zeros32 =np.zeros((3,2))
print(zeros32)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


array filled with ones -   np.ones()

In [19]:
ones = np.ones(3)
print(ones)
ones1=np.ones((4,3))
print(ones1)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


creating an empty array   - empty()


In [20]:
empty = np.empty(4)
print(empty)

[0. 0. 0. 0.]


using arrange function - arange()

In [22]:
array = np.arange(4)
print(array)

[0 1 2 3]


creating an digonal element array - 
[1 0 0]
[0 1 0]
[0 0 1]     using - eye function for this 

In [23]:
diagonal_array =np.eye(4)
print(diagonal_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


line space use to create array - linspace() method

In [25]:
linespace = np.linspace(0,5,num = 4)
print(linespace)

[0.         1.66666667 3.33333333 5.        ]


creating arrays with random numbers  - random()

rand() function - use to generate random values between zero to one 

In [28]:
random_array = np.random.rand(4)
print(random_array)

[0.47662317 0.98760064 0.5068652  0.51027227]


In [29]:
random_array = np.random.rand(4,5)
print(random_array)

[[0.56463387 0.61121427 0.76551207 0.3095768  0.90356924]
 [0.79886172 0.27731118 0.93413763 0.89474768 0.48602993]
 [0.48115768 0.61365884 0.82344901 0.33170829 0.99105128]
 [0.72513796 0.57405709 0.22142864 0.69955055 0.15780998]]


randn() - this is the function used to generate random value close ot zero ,this may return positive or negative numbers as well

In [31]:
randn= np.random.randn(5)
print(randn)

[ 1.42056092  0.44623706 -0.14388625  0.07009123  1.42309414]


In [33]:
randn = np.random.randn(3,4)
print(randn)

[[-0.09067903 -1.76017225  1.51133043 -0.09731506]
 [-0.56594674 -0.70001345  1.26491137 -0.12373954]
 [ 0.00636978 -0.06976331 -0.09491435 -0.05276097]]


randf() - this function is used to generate random sampling in in numpy , it returns the array of specified shape and fill it with radom floats in the half open intervell 

In [35]:
 randf = np.random.ranf(3)
print(randf)

[0.54266397 0.5467437  0.33828347]


randint() - it is the function used to generate random numbers in a given range  - randint(min,max,total_values)

In [37]:
random_int=np.random.randint(1,6,5)
print(random_int)

[5 1 3 1 4]


In [ ]:
data types in numpy arrays - bool , int ,float , complex

In [ ]:
example code to find the database using the dtype function -- dtype()

In [39]:
array= np.array([1,2,3,5])
print("the data type",array.dtype)

the data type int32


In [40]:
# converting the data type to int8

array= np.array([1,2,3,5],dtype=np.int8)
print("the data type",array.dtype)

the data type int8


In [46]:
# another method is used to convert the data type 

array=np.array([1,2,3,4])
print(array)

float=np.float_(array)
print(float)
int=np.int_(float)
print(int)


[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


Generate an array of 20 random integers between 1 and 100.

In [49]:
random=np.random.randint(1,100,20)
print(random)

[91 57 48 69 85 70 16 70 32 52 63 90 33 52 13 68 30  6 66 29]


Basic Array Manipulation


Create an Array:

1)Generate an array of 20 random integers between 1 and 100.                                    #completed
2)Create an array of 10 elements all set to zero, except the fifth element, which should be 1.


Array Reshaping:

Convert a 1D array of 12 elements to a 3x4 matrix.                                              #completed
Given an array a = np.array([1, 2, 3, 4, 5, 6]), reshape it into a 2x3 matrix.


Array Indexing and Slicing:

Given an array of 25 elements (e.g., np.arange(1, 26)), select only the elements at odd indices. #completed
Reverse the elements in an array without using a loop.


Element-wise Operations:

Create two arrays, a and b, and add them element-wise.                            #completed
    Compute the element-wise multiplication of two matrices, a and b.b


Statistical Operations

Mean and Standard Deviation:

Given an array of numbers, calculate the mean and standard deviation.
Find the median of an array with 15 random integers.                          # completed
Max and Min:

Generate a 4x4 matrix of random numbers and find the maximum value in each row.
Find the minimum value in an array and its index.


Conditional Operations

Filtering with Conditions:

Given an array a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), filter out all even numbers.         #completed
Generate a random array of 20 elements between 1 and 100 and replace all elements greater than 50 with 0.



Where and Select Functions:

Use np.where to replace all negative values in an array with zero.                    #completed
Given two arrays a and b, use np.where to return elements from a where a > b and from b otherwise.

Linear Algebra

Dot Product and Cross Product:

Calculate the dot product of two vectors a and b.     #completed

Given two 3D vectors, find their cross product.


matrix Multiplication:

Create two matrices, A (3x2) and B (2x3), and calculate the matrix product A * B.
Verify the dimensions of A and B to see if they are compatible for multiplication.       #completed


Eigenvalues and Eigenvectors:

Find the eigenvalues and eigenvectors of a 3x3 matrix.
Check if a matrix is singular by calculating its determinant.
Miscellaneous Calculations


Cumulative Sum:

Find the cumulative sum of an array with 10 random integers.    #completed
Compute the cumulative product of a list of numbers.


Sorting and Unique:

Sort an array of random numbers in ascending and descending order.  #completed
Find unique elements in an array and count their occurrences.


Random Sampling:

Generate an array of 10 random floats between 0 and 1.
Create a 5x5 matrix with random values sampled from a normal distribution.   #completed


Reshaping and Stacking:

Stack two arrays vertically and horizontally.
Split an array of 20 elements into 4 arrays with 5 elements each.
Advanced Questions                        #completed

Solve a System of Equations:

Solve the system of equations:
3
𝑥
+
2
𝑦
=
12
5
𝑥
+
𝑦
=
14
3x+2y=12
5x+y=14
Polynomial Fit:

Fit a polynomial of degree 2 to the points (0,1), (1,3), (2,7), and (3,13).
Evaluate the polynomial at x = 4.
Fourier Transform:

In [61]:
# Create an array of 10 elements all set to zero, except the fifth element, which should be 1.

array = np.zeros(10)
array[4]=5
print(array)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


arithmatic operation using an array  in one dimensional array 

addition -  np.add()

In [64]:
# // normal operation without using the funcion 

array= np.array([1,2,3,4])
array2 = np.array([2,3,4,5])
var= array+array2
var

array([3, 5, 7, 9])

In [65]:
# deviding

a= np.array([1,2,3,4])
c=a/3
print(c)

[0.33333333 0.66666667 1.         1.33333333]


In [66]:
# modulas

a= np.array([4,5,6,7])
c=a%4
print(c)

[0 1 2 3]


In [68]:
# using functions for this 
# np.add()

arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
c=np.add(arr1,arr2)
print(c)

[ 4  6  8 10]


In [70]:
# using substract function for this 
# np.subtract()
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
c=np.subtract(arr1,arr2)
print(c)


[-2 -2 -2 -2]


In [72]:
# using multiply function for this 
# np.multiply()
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
c=np.multiply(arr1,arr2)
print(c)

[ 3  8 15 24]


In [74]:
# using divide function for this 
# np.divide()
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
c=np.divide(arr1,arr2)
print(c)

[0.33333333 0.5        0.6        0.66666667]


In [75]:
# using mode function for this 
# np.mod()
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
c=np.mod(arr1,arr2)
print(c)

[1 2 3 4]


In [76]:
# using power function for this 
# np.power()
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
c=np.power(arr1,arr2)
print(c)

[   1   16  243 4096]


In [77]:
# using reciprocal function for this 
# np.reciprocal()
arr1=np.array([1,2,3,4])

c=np.reciprocal(arr1)
print(c)

[1 0 0 0]


two dimension array using for mathematical calculation 

In [81]:
# using add() function to add arrays 
# np.add()

arr1 =np.array([[1,2,3,4],[4,5,6,7]])
arr2 =np.array([[1,2,3,4],[4,5,6,7]])

add=np.add(arr1,arr2)
print(add)

[[ 2  4  6  8]
 [ 8 10 12 14]]


In [86]:
# adding a random number to the two dimensional array

array=np.array([[1,2,3,4],[4,5,6,7]])
c=np.random.randint(1,10)
print(c)
adding= array+c
print(adding)

4
[[ 5  6  7  8]
 [ 8  9 10 11]]


In [90]:
# using multiplication operation on two dimensional arrays 

array1=np.array([[1,2,3,4],[4,5,6,7]])
array2=np.array([[1,2,5,4],[4,5,4,7]])
c= np.multiply(array1,array2)
print(c)

[[ 1  4 15 16]
 [16 25 24 49]]


In [94]:
# using the dot operator to use the matrix multiplication operation
# np.dot()  or @

array1=np.array([[1,2,3,4],[4,5,6,7],[4,5,6,7],[9,8,6,6]])
array2=np.array([[1,2,5,4],[4,5,4,7],[4,5,6,7],[9,8,6,6]])
c= np.dot(array1,array2)
v=array1@array2
print(c)
print(v)



[[ 57  59  55  63]
 [111 119 118 135]
 [111 119 118 135]
 [119 136 149 170]]
[[ 57  59  55  63]
 [111 119 118 135]
 [111 119 118 135]
 [119 136 149 170]]


some more arithmatic function 

np.min(x) -using to find minimum 
np.max(x) -using to find the maximum
np.argmin(x)-using to find the argument it means its index number will show ,another function for max index finding which is 
np.argmax(x)
np.sqrt(x)- using to find the squre root 
np.sin(x) -using ot find the sine
np.cos(x) -finding the cos of the array 
np.cumsum(x) - is the cumulative sum of the number

also axis 0 is column 
     axis 1 is row 



In [103]:
array = np.array([1,2,3,4,5])
print("minimum of the array:",min(array),np.argmin(array))
print("maximum of the array",np.max(array),np.argmax(array))


minimum of the array: 1 0
maximum of the array 5 4


finding the minimum and maximum of two dimensional array 

In [106]:
array = np.array([[1,2,3,4],[5,6,7,8]])
print(array)
# axis zero is for column
print("the maximum number in x axis :",np.max(array,axis=0))
# axis one is row
print("the maximum number in x axis :",np.max(array,axis=1))

[[1 2 3 4]
 [5 6 7 8]]
the maximum number in x axis : [5 6 7 8]
the maximum number in x axis : [4 8]


In [109]:
# finding the minimum and maximum argument in the two dimensional array in column wise
array = np.array([[1,2,3,4],[5,6,7,8]])
# finding the minimum using argmin() function in column 
print("the minimal argument:",np.argmin(array,axis=0))
# finding the maximum index of the value using argmax() funciton in column
print("the max index :" ,np.argmax(array,axis=0))

the minimal argument: [0 0 0 0]
the max index : [1 1 1 1]


In [110]:
# finding the minimum and maximum argument in the two dimensional array in row wise
array = np.array([[1,2,3,4],[5,6,7,8]])
# finding the minimum using argmin() function in row
print("the minimal argument:",np.argmin(array,axis=1))
# finding the maximum index of the value using argmax() funciton in row
print("the max index :" ,np.argmax(array,axis=1))

the minimal argument: [0 0]
the max index : [3 3]


finding the squre root of normal array

In [111]:
array = np.array([1,2,3,4])
print(np.sqrt(array))

[1.         1.41421356 1.73205081 2.        ]


finding the squre root of the multidimensional array

In [114]:
array=np.array([[1,2,3,4],[2,3,5,7]])
print(np.sqrt(array))

[[1.         1.41421356 1.73205081 2.        ]
 [1.41421356 1.73205081 2.23606798 2.64575131]]


In [115]:
# // sin of the array 
array=np.array([[1,2,3,4],[2,3,5,7]])
print(np.sin(array))

[[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [ 0.90929743  0.14112001 -0.95892427  0.6569866 ]]


In [116]:
# printing the cos of the array
array=np.array([[1,2,3,4],[2,3,5,7]])
print(np.cos(array))

[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [-0.41614684 -0.9899925   0.28366219  0.75390225]]


In [117]:
# finding the cumulative sum of the array 
array=np.array([[1,2,3,4],[2,3,5,7]])
print("cumulative sum of the array :",np.cumsum(array))



cumulative sum of the array : [ 1  3  6 10 12 15 20 27]


reshaping the numpy array 

shape() - it is used to find the rows and colums of the array 

In [119]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
print(arr.shape)



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [124]:
# fiding the shape of the one dimensional array 

array = np.array([1,2,3])
print(array.shape)

(3,)


In [126]:
# shape of two dimensional array 
array =np.array([[1,2,3],[4,5,6]])
print(array.shape)

(2, 3)


In [134]:
#shape of n dimensional array

array=np.array([1,2,3],ndmin=4)
print(array)
print(array.shape)
print(array.ndim)

[[[[1 2 3]]]]
(1, 1, 1, 3)
4


In [137]:
array= np.array([[1,2,3,4],[4,5,6,7]],ndmin=5)
print(array)
print(array.shape)


[[[[[1 2 3 4]
    [4 5 6 7]]]]]
(1, 1, 1, 2, 4)


reshaping the entire array into defferent type

In [143]:
#reshaping the normal one dimensional array into two dimensional array 
# here array has six element , which means we can reshape into six elements   

array=np.array([1,2,3,4,5,6])
print(array.shape)
array1=array.reshape(3,2)
print(array1.shape)
print(array.reshape(6,1))
print(array1)
print(array1.ndim)

(6,)
(3, 2)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2]
 [3 4]
 [5 6]]
2


In [149]:
#reshape()  with three argument  blocknumber , rows , columns

array= np.array([1,2,3,4,5,6])
x=array.reshape(2,1,3)
print(x)
print(x.shape)

print(x.ndim)
print(x.reshape(-1))  #converting into one dimension again 

[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)
3
[1 2 3 4 5 6]


1)Convert a 1D array of 12 elements to a 3x4 matrix.                              
2)Given an array a = np.array([1, 2, 3, 4, 5, 6]), reshape it into a 2x3 matrix.


In [153]:

# 1)
array= np.arange(1,12+1)
print(array)

x=array.reshape(3,4)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [154]:
# 2) 
a = np.array([1, 2, 3, 4, 5, 6])
print(a.reshape(2,3))



[[1 2 3]
 [4 5 6]]


broad casting in numpy array

it is the ability to perform operations between arrays of different types
the shapes should be compatible 
and also fro the rightside raw should be equal

In [165]:
array1=np.array([1,2,3,4])
print(array1.shape)
array2=np.array([1,2,4,4])
print(array2.shape)
x=array1+array2
print(x)

(4,)
(4,)
[2 4 7 8]


In [174]:
a=np.arange(6).reshape(3,2)
print(a)
print(a.shape)
print(a.ndim)
print()
b=np.arange(4).reshape(2,2)
print(b)
print(b.shape)
print(b.ndim)

# it wont strech because it is diemension from the right is currect but ,
# the dimension after  the right is not currect 

[[0 1]
 [2 3]
 [4 5]]
(3, 2)
2

[[0 1]
 [2 3]]
(2, 2)
2


In [176]:
a=np.arange(9).reshape(3,3)
print(a)

b=np.arange(3).reshape(1,3)
print(b)
x=a+b
print(x)
# this is working

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


indexing and slicing and iterating in numpy array

In [193]:

it is the indexing of the array element of three dimension 

a=np.arange(12).reshape(3,2,2)

print(a)
print(a.shape)
print()
print(a[0,1,1])


[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
(3, 2, 2)

3


slicing in numpy arrays
slicing method - [start,stop,step]

In [207]:
a=np.arange(12).reshape(1,12)
print(a)
print(a.ndim)

print(a[0,0:])
print(a[0,0:6])

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
2
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5]


1)Given an array of 25 elements (e.g., np.arange(1, 26)), select only the elements at odd indices. 
2)Reverse the elements in an array without using a loop.

In [214]:
a=np.arange(1,26)
print(a)
# print(a[::2])  1) is finding here
# print(a[::-1])   2) is finding here

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1]


In [ ]:
1)Given an array of numbers, calculate the mean and standard deviation.   np.mean() and np.std()
2)Find the median of an array with 15 random integers.                        
Max and Min:

In [223]:
a=np.arange(1,10)
print(a)
print("the mean is",np.mean(a))
print("the standard deviation is ",np.std(a))
print("the standard max is ",max(a))
print("the standard min is ",min(a))

[1 2 3 4 5 6 7 8 9]
the mean is 5.0
the standard deviation is  2.581988897471611
the standard max is  9
the standard min is  1


In [227]:
a=np.arange(12).reshape(4,3)
print(a.ndim)

print("the standard deviation of this array",np.std(a))
print("the standard deveiation amoung row",np.std(a,axis=1))
print("the standard deviation amound columns",np.std(a ,axis=0))

2
the standard deviation of this array 3.452052529534663
the standard deveiation amoung row [0.81649658 0.81649658 0.81649658 0.81649658]
the standard deviation amound columns [3.35410197 3.35410197 3.35410197]


iterating trough the array --using for loop to iterate through the array 

In [229]:
array= np.arange(20)
print(array)

for i in array :
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [232]:
a= np.arange(12).reshape(3,4)
print(a)
for i in a:
    for j in i:
        print(j)
        
#when the dimension is increasing we have to use more nested loop for this 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


nditer() function -- it is used to remove the struggle of using inner for loops 


In [237]:
a=np.arange(12).reshape(3,4)

for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


using ndenumerate  - it is used to print the index and data 

In [241]:
a=np.arange(12).reshape(2,3,2)
print(a)

for i,d in np.ndenumerate(a):
    print(i,d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(0, 2, 0) 4
(0, 2, 1) 5
(1, 0, 0) 6
(1, 0, 1) 7
(1, 1, 0) 8
(1, 1, 1) 9
(1, 2, 0) 10
(1, 2, 1) 11


copy and view function using numpy array 

In [242]:
# copy function in numpy 

var=np.arange(10)
print(var)
x=var.copy()
print("it is the copy",x)

[0 1 2 3 4 5 6 7 8 9]
it is the copy [0 1 2 3 4 5 6 7 8 9]


In [249]:
#using view function 
a=np.arange(10)
print(a)
vi=a.view()
print(vi)
a[2]=5
print(a)
print(vi)

# the only difference between the view and the copy function the function of copy the data is same , but in view when ever
# we change the orginal data it is affect in the view , but in copy it wont affect 

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 5 3 4 5 6 7 8 9]
[0 1 5 3 4 5 6 7 8 9]


joining and splitting the array
concatenate()  this is used to merge two one dimensional arrays 


In [253]:
a=np.arange(6)
b=np.arange(3)
print(a)
print(b)

v=np.concatenate((a,b))
print(v)

[0 1 2 3 4 5]
[0 1 2]
[0 1 2 3 4 5 0 1 2]


In [257]:
a=np.arange(6).reshape(3,2)
print(a)
b=np.arange(6).reshape(3,2)
print(b)

v=np.concatenate((a,b),axis=1)  #row waise merging using 
print(v)


[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]]


In [258]:
a=np.arange(6).reshape(3,2)
print(a)
b=np.arange(6).reshape(3,2)  #using stack
print(b)

v=np.stack((a,b),axis=1)  
print(v)

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[[0 1]
  [0 1]]

 [[2 3]
  [2 3]]

 [[4 5]
  [4 5]]]


In [259]:
a=np.arange(6).reshape(3,2)
print(a)
b=np.arange(6).reshape(3,2)  #using stack
print(b)

v=np.stack((a,b),axis=0)  
print(v)

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]]


splitting array 

breaking one array into multiple 

In [268]:
a=np.arange(4).reshape(2,2)
print(a)

v=np.array_split(a,2)
v1=np.array_split(a,3,axis=1)
print(v1)
print(v)

[[0 1]
 [2 3]]
[array([[0],
       [2]]), array([[1],
       [3]]), array([], shape=(2, 0), dtype=int32)]
[array([[0, 1]]), array([[2, 3]])]


Given an array a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), filter out all even numbers.
Generate a random array of 20 elements between 1 and 100 and replace all elements greater than 50 with 0.

In [270]:
a=np.arange(1,11)
print(a)
for i in np.nditer(a):
    if i%2==0:
        print(i)

[ 1  2  3  4  5  6  7  8  9 10]
2
4
6
8
10


In [273]:


a=np.random.randint(1,100,20)
a[a>50]=0
print(a)
        
    

[ 0  0  0  0  0 12  0  0  0 16 12  0 41 47  0 39  0  0  0 49]


search method using in array - search array for a certain value and return indexes that get a match 

In [275]:
# where method is used here  np.where()

a=np.arange(10)
print(a)

select= np.where(a%2==0)
print(select)

[0 1 2 3 4 5 6 7 8 9]
(array([0, 2, 4, 6, 8], dtype=int64),)


In [ ]:
search sorted array - wich poerforms a binary search in the array , and return the index where the specified value would be inserted 
to maintain the search order 

In [ ]:
using search sorted array method - np.searchsorted()

In [280]:
a=np.arange(10)
print(a)
print()
x1=np.searchsorted(a,6.5,side="right")  #using the search sort method for  this 
print(x1)






[0 1 2 3 4 5 6 7 8 9]

7


sorted array - orderd sequence is any sequence that has an orderd curresponding to element. - sort()

In [282]:
a=np.arange(6)
print(a)
print(np.sort(a))

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [284]:
#use randint function to sort the array

a=np.random.randint(1,10,6)
print(a)
print(np.sort(a))

[3 1 3 6 8 1]
[1 1 3 3 6 8]


In [288]:
#sorting two dimensional arrays 

a=np.random.randint(1,100,12).reshape(4,3)
print(a)
print(np.sort(a,axis=0))
print(np.sort(a,axis=1))

[[ 5 73 45]
 [50 70 83]
 [50 75 69]
 [92 48 39]]
[[ 5 48 39]
 [50 70 45]
 [50 73 69]
 [92 75 83]]
[[ 5 45 73]
 [50 70 83]
 [50 69 75]
 [39 48 92]]


filtering  the array use flter method - getting some element out of an existing array and creating a new array out of them  

In [296]:
#filters is using 

a=np.random.randint(1,10,6)
print(a)
f=[a>6]
f1=a[a>6]
print(f)
print(f1)

[8 2 4 2 9 7]
[array([ True, False, False, False,  True,  True])]
[8 9 7]


In [ ]:
other arithmatic functions 

shuffle
unique
resize
flatten
ravel

In [304]:
#using shuffle method for this 
b=np.arange(10)
np.random.shuffle(b)
print(b)


[7 0 6 9 2 1 8 3 5 4]
None


In [310]:
#using unoque method for this 

a=np.random.randint(1,10,5)
b=np.unique(a)
print(a)
print(b)

[7 9 9 3 4]
[3 4 7 9]


In [317]:
#using resize function 

var= np.arange(10)
print(var)
# print(np.resize(var,(5,2)))
v=np.resize(var,(5,2)

#using flatten 
            
print(v.flatten())
            
#same funciton is this in another format which is ravel()bb



SyntaxError: invalid syntax (3344809212.py, line 10)

numpy using insert and delete method 

In [323]:
#usng insert method to insert some data to the array

a=np.arange(6)
print(a)

c=np.insert(a,3,7)
v=np.insert(a,2,[5,6]) #inserting list of elements 
print(v)
print(c)

[0 1 2 3 4 5]
[0 1 5 6 2 3 4 5]
[0 1 2 7 3 4 5]


In [326]:
#inserting elements to the two dimensional arrays 

a=np.arange(6).reshape(3,2)
print(a)

c=np.insert(a,1,3,axis=0)
print(c)

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [3 3]
 [2 3]
 [4 5]]


In [331]:
#using delete it will use the index and remove index 

a=np.arange(1,6)
print(a)

v=np.delete(a,1)
print(v)

[1 2 3 4 5]
[1 3 4 5]


In [334]:
#using delete for the multidimensional arrays 

a=np.arange(6).reshape(3,2)
print(a)


n=np.delete(a,1)
print(n)

[[0 1]
 [2 3]
 [4 5]]
[0 2 3 4 5]


mutrix in numpy arrays 

In [337]:
a=np.matrix([1,2,3,4])
print(a)
print(type(a))

[[1 2 3 4]]
<class 'numpy.matrix'>


matrix calculations 

transpose
sawapaxes 
inverse
determinant 
power


In [338]:
#using transpose  in matrix 
a=np.matrix([1,2,3,4])
print(np.transpose(a))


[[1]
 [2]
 [3]
 [4]]


In [341]:
#using swapaxis 
a=np.matrix([1,2,3,4])
print(np.swapaxes(a,0,1))


[[1]
 [2]
 [3]
 [4]]


In [345]:
#using swapaxis 
a=np.matrix([[1,2,3,4],[1,5,3,7]])
print(np.linalg.inv(a))


LinAlgError: Last 2 dimensions of the array must be square